library(shiny); library(DT); library(DBI); library(duckdb)
repo_root <- normalizePath(if (file.exists("parsing/initDb.py")) "." else "..", mustWork=TRUE)
script05 <- file.path(repo_root,"R_Scripts","05_Download_Metadata_Inventory.R")
ui <- fluidPage(titlePanel("GEO Download and Sample Explorer"), sidebarLayout(
 sidebarPanel(textInput("workbook","Excel workbook","/Users/fauzanahmed/Downloads/Heme_Cancer_GEO_Inventory.xlsx"), textInput("query","GEO keyword query (optional)"), textInput("out_dir","Output directory",file.path(repo_root,"downloads","shiny_download")), textInput("db_path","DuckDB path",file.path(repo_root,"data","geo.db")), textInput("diagnosis","Diagnosis name","heme_cancer"), actionButton("run","Download, update DB, and explore",class="btn-primary")),
 mainPanel(h4(textOutput("status")),verbatimTextOutput("log"),tabsetPanel(tabPanel("Downloaded",DTOutput("downloaded")),tabPanel("Failures",DTOutput("failures")),tabPanel("Datasets",DTOutput("datasets")),tabPanel("Samples",DTOutput("samples"))))) )
server <- function(input,output,session) {
 status <- reactiveVal("Ready."); logtxt <- reactiveVal(""); version <- reactiveVal(0L); con <- reactiveVal(NULL)
 refresh <- function(){ old<-con(); if(!is.null(old)) try(dbDisconnect(old,shutdown=TRUE),silent=TRUE); if(file.exists(input$db_path)) con(dbConnect(duckdb(),input$db_path,read_only=TRUE)); version(version()+1L) }
 observeEvent(input$run,{ useq<-nzchar(trimws(input$query)); if(!useq && !file.exists(input$workbook)){status("Workbook not found.");return()}; dir.create(input$out_dir,recursive=TRUE,showWarnings=FALSE); status("Running download..."); args<-if(useq)c("--vanilla",script05,"--query",input$query,"--out",input$out_dir) else c("--vanilla",script05,input$workbook,input$out_dir); r<-tryCatch(system2("Rscript",args,stdout=TRUE,stderr=TRUE),error=function(e)paste("ERROR:",conditionMessage(e))); if(any(grepl("ERROR|Execution halted",r))){logtxt(paste(r,collapse="\n"));status("Download failed.");return()}; status("Updating database..."); old<-con(); if(!is.null(old)){try(dbDisconnect(old,shutdown=TRUE),silent=TRUE);con(NULL)}; if(!file.exists(input$db_path)) system2("python",c(file.path(repo_root,"parsing","initDb.py"),"--db-path",input$db_path,"--diagnosis",input$diagnosis),stdout=TRUE,stderr=TRUE); u<-system2("python",c(file.path(repo_root,"parsing","updateDb.py"),file.path(input$out_dir,"matrices"),"--db-path",input$db_path,"--diagnosis",input$diagnosis,"--report",file.path(input$out_dir,"db_update_report.tsv")),stdout=TRUE,stderr=TRUE); logtxt(paste(c(r,u),collapse="\n")); status("Complete. Database and reports updated."); refresh() })
 output$status<-renderText(status()); output$log<-renderText(logtxt()); report<-function(n){p<-file.path(input$out_dir,n);if(!file.exists(p))return(data.frame(Message="No report yet."));read.csv(p,check.names=FALSE)}
 output$downloaded<-renderDT({version();datatable(report("downloaded_matrices.csv"),filter="top",options=list(pageLength=25,scrollX=TRUE))}); output$failures<-renderDT({version();datatable(report("failures.csv"),filter="top",options=list(pageLength=25,scrollX=TRUE))})
 query<-function(sql){x<-con();req(!is.null(x));dbGetQuery(x,sql)}
 output$datasets<-renderDT({version();datatable(query("select * from dataset order by dataset_id"),filter="top",options=list(pageLength=25,scrollX=TRUE))}); output$samples<-renderDT({version();datatable(query("select * from sample order by sample_id"),filter="top",options=list(pageLength=25,scrollX=TRUE))})
 session$onSessionEnded(function(){if(!is.null(con()))dbDisconnect(con(),shutdown=TRUE)})
}
shinyApp(ui,server)
